return {
  "stevearc/oil.nvim",
  opts = {
    default_file_explorer = true,
    keymaps = {
      ["g?"] = "actions.show_help",
      ["<CR>"] = "actions.select",
      ["<Tab>"] = "actions.select",
      ["<C-v>"] = { "actions.select", opts = { vertical = true } },
      -- ["<C-h>"] = { "actions.select", opts = { horizontal = true } },
      ["<C-t>"] = { "actions.select", opts = { tab = true } },
      ["<C-p>"] = "actions.preview",
      -- ["<C-c>"] = { "actions.close", mode = "n" },
      -- ["<C-l>"] = "actions.refresh",
      -- ["_"] = { "actions.open_cwd", mode = "n" },
      ["_"] = { "actions.parent", mode = "n" },
      ["`"] = { "actions.cd", mode = "n" },
      ["~"] = { "actions.cd", opts = { scope = "tab" }, mode = "n" },
      ["gs"] = { "actions.change_sort", mode = "n" },
      ["gx"] = "actions.open_external",
      ["g."] = { "actions.toggle_hidden", mode = "n" },
      ["g\\"] = { "actions.toggle_trash", mode = "n" },
      -- ["<C-h>"] = false,
      ["<C-r>"] = "actions.refresh",
      ["-"] = "actions.parent",
      ["<S-Tab>"] = "actions.parent",
    },
    use_default_keymaps = false,
    view_options = {
      show_hidden = true,
    },
  },
  dependencies = { "nvim-tree/nvim-web-devicons" },
}
