 font=ComicShannsMono Nerd Font Mono:size=13
# font=DejaVuSansMono Nerd Font Mono:size=13
# font=GeistMono Nerd Font Mono:size=13

[main]
shell=herdr
# include=~/.config/foot/themes/tokyonight-night.ini
include=~/.config/foot/themes/catppuccin-mocha.ini

